name: Semgrep Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write 

jobs:
  semgrep:
    name: Run Semgrep Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep scan with SARIF output
        run: |
          semgrep --config p/owasp-top-ten --sarif > semgrep.sarif || true

      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Show link to Code Scanning results
        run: |
          echo "🔍 Veja os resultados em: https://github.com/${{ github.repository }}/security/code-scanning"
